In [2]:
import pandas as pd

Test_data = pd.read_csv('face_analysis_results.csv')
Test_data

              Image  Age Gender             Race
0  image0021846.jpg   29    Man           indian
1  image0021851.jpg   52  Woman            white
2  image0021869.jpg   47    Man            white
3  image0021894.jpg   23    Man  latino hispanic
4  image0021941.jpg   39    Man            white
5  image0021955.jpg   35    Man  latino hispanic

In [3]:
Test_data['Race'].unique()

array(['indian', 'white', 'latino hispanic'], dtype=object)

In [18]:
# List of DataFrames to merge
dfs = [annot1_data, annot2_data, Test_data]

# Merge all DataFrames on 'Image' using reduce and pd.merge
merged_data = reduce(lambda left, right: pd.merge(left, right, on='Image'), dfs)

# Optionally, save the merged data to a new CSV file
merged_data.to_csv('merged_annotations_and_analysis.csv', index=False)

# Rename columns for clarity
merged_data = merged_data.rename(columns={
    'Age_x': 'Age_manual_1',
    'Gender_x': 'Gender_manual_1',
    'Race_x': 'Race_manual_1',
    'Annotation_by_x': 'Annotation_by_manual_1',
    'Age_y': 'Age_manual_2',
    'Gender_y': 'Gender_manual_2',
    'Race_y': 'Race_manual_2',
    'Annotation_by_y': 'Annotation_by_manual_2',
    'Age': 'Age_automatic',
    'Gender': 'Gender_automatic',
    'Race': 'Race_automatic'
})

# Define a function to create age groups
def create_age_group(age):
    if age < 20:
        return '0-19'
    elif 20 <= age < 30:
        return '20-29'
    elif 30 <= age < 40:
        return '30-39'
    elif 40 <= age < 50:
        return '40-49'
    elif 50 <= age < 60:
        return '50-59'
    else:
        return '60+'

# Apply the age group function to all age columns (manual and automatic)
merged_data['Age_group_manual_1'] = merged_data['Age_manual_1'].apply(create_age_group)
merged_data['Age_group_manual_2'] = merged_data['Age_manual_2'].apply(create_age_group)
merged_data['Age_group_automatic'] = merged_data['Age_automatic'].apply(create_age_group)

merged_data

,Image,Age_manual_1,Gender_manual_1,Race_manual_1,Annotation_by_manual_1,Age_manual_2,Gender_manual_2,Race_manual_2,Annotation_by_manual_2,Age_automatic,Gender_automatic,Race_automatic,Age_group_manual_1,Age_group_manual_2,Age_group_automatic
0,image0021846.jpg,65.0,Man,middle eastern,ldk,58,Man,middle eastern,2,29,Man,indian,60+,50-59,20-29
1,image0021851.jpg,56.0,Woman,white,ldk,56,Woman,white,2,52,Woman,white,50-59,50-59,50-59
2,image0021894.jpg,29.0,Woman,white,ldk,29,Woman,latino hispanic,2,23,Man,latino hispanic,20-29,20-29,20-29
3,image0021941.jpg,39.0,Man,white,ldk,56,Man,white,2,39,Man,white,30-39,50-59,30-39
4,image0021869.jpg,65.0,man,latino hispanic,ldk,65,Man,latino hispanic,2,47,Man,white,60+,60+,40-49
5,image0021955.jpg,45.0,Man,indian,ldk,55,Man,indian,2,35,Man,latino hispanic,40-49,50-59,30-39

# 1. (Dis)agreement Metrics:
We’ll calculate the agreement between the two manual annotations and the automatic annotations for Gender, Race, and Age.

Gender Agreement:
- Manual 1 vs Automatic
- Manual 2 vs Automatic

Race Agreement:
- Manual 1 vs Automatic
- Manual 2 vs Automatic

In [19]:
# Gender agreement between Manual 1 and Automatic
gender_agreement_manual1_automatic = (merged_data['Gender_manual_1'] == merged_data['Gender_automatic']).mean() * 100

# Gender agreement between Manual 2 and Automatic
gender_agreement_manual2_automatic = (merged_data['Gender_manual_2'] == merged_data['Gender_automatic']).mean() * 100

print(f"Gender Agreement between Manual 1 and Automatic: {gender_agreement_manual1_automatic}%")
print(f"Gender Agreement between Manual 2 and Automatic: {gender_agreement_manual2_automatic}%")

# Race agreement between Manual 1 and Automatic
race_agreement_manual1_automatic = (merged_data['Race_manual_1'] == merged_data['Race_automatic']).mean() * 100

# Race agreement between Manual 2 and Automatic
race_agreement_manual2_automatic = (merged_data['Race_manual_2'] == merged_data['Race_automatic']).mean() * 100

print(f"Race Agreement between Manual 1 and Automatic: {race_agreement_manual1_automatic}%")
print(f"Race Agreement between Manual 2 and Automatic: {race_agreement_manual2_automatic}%")

# Calculate agreement between Manual 1 and Automatic for Age Groups
age_group_agreement_manual1_automatic = (merged_data['Age_group_manual_1'] == merged_data['Age_group_automatic']).mean() * 100

# Calculate agreement between Manual 2 and Automatic for Age Groups
age_group_agreement_manual2_automatic = (merged_data['Age_group_manual_2'] == merged_data['Age_group_automatic']).mean() * 100

# Calculate agreement between Manual 1 and Manual 2 for Age Groups
age_group_agreement_manual1_manual2 = (merged_data['Age_group_manual_1'] == merged_data['Age_group_manual_2']).mean() * 100

# Display the results
print(f"Age Group Agreement between Manual 1 and Automatic: {age_group_agreement_manual1_automatic}%")
print(f"Age Group Agreement between Manual 2 and Automatic: {age_group_agreement_manual2_automatic}%")
print(f"Age Group Agreement between Manual 1 and Manual 2: {age_group_agreement_manual1_manual2}%")

Gender Agreement between Manual 1 and Automatic: 66.66666666666666%
Gender Agreement between Manual 2 and Automatic: 83.33333333333334%
Race Agreement between Manual 1 and Automatic: 33.33333333333333%
Race Agreement between Manual 2 and Automatic: 50.0%
Age Group Agreement between Manual 1 and Automatic: 50.0%
Age Group Agreement between Manual 2 and Automatic: 33.33333333333333%
Age Group Agreement between Manual 1 and Manual 2: 50.0%

# 2. Bias Detection:
To investigate bias, we can check if certain races are consistently over/underpredicted compared to manual annotations.

In [20]:
# Bias in Race predictions (Manual 1 vs Automatic)
race_bias_manual1_automatic = merged_data.groupby(['Race_manual_1', 'Race_automatic']).size().unstack(fill_value=0)
print("Race Bias (Manual 1 vs Automatic):")
print(race_bias_manual1_automatic)

# Bias in Race predictions (Manual 2 vs Automatic)
race_bias_manual2_automatic = merged_data.groupby(['Race_manual_2', 'Race_automatic']).size().unstack(fill_value=0)
print("Race Bias (Manual 2 vs Automatic):")
print(race_bias_manual2_automatic)

Race Bias (Manual 1 vs Automatic):
Race_automatic   indian  latino hispanic  white
Race_manual_1
indian                0                1      0
latino hispanic       0                0      1
middle eastern        1                0      0
white                 0                1      2
Race Bias (Manual 2 vs Automatic):
Race_automatic   indian  latino hispanic  white
Race_manual_2
indian                0                1      0
latino hispanic       0                1      1
middle eastern        1                0      0
white                 0                0      2

# 3. Agreement Metrics by Category:
You can calculate agreement by category (e.g., by Gender or Race) to see how well the automatic system agrees with manual annotations in specific subgroups.

Agreement by Gender:

In [24]:
# Agreement by Gender (Manual 1 vs Automatic)
gender_group_agreement_manual1 = merged_data.groupby('Gender_manual_1').apply(
    lambda x: (x['Gender_manual_1'] == x['Gender_automatic']).mean() * 100)

# Agreement by Gender (Manual 2 vs Automatic)
gender_group_agreement_manual2 = merged_data.groupby('Gender_manual_2').apply(
    lambda x: (x['Gender_manual_2'] == x['Gender_automatic']).mean() * 100)

print("Gender Agreement by Gender (Manual 1 vs Automatic):")
print(gender_group_agreement_manual1)

print("Gender Agreement by Gender (Manual 2 vs Automatic):")
print(gender_group_agreement_manual2)

Gender Agreement by Gender (Manual 1 vs Automatic):
Gender_manual_1
Man      100.0
Woman     50.0
man        0.0
dtype: float64
Gender Agreement by Gender (Manual 2 vs Automatic):
Gender_manual_2
Man      100.0
Woman     50.0
dtype: float64

In [25]:
# Agreement by Race (Manual 1 vs Automatic)
race_group_agreement_manual1 = merged_data.groupby('Race_manual_1').apply(
    lambda x: (x['Race_manual_1'] == x['Race_automatic']).mean() * 100)

# Agreement by Race (Manual 2 vs Automatic)
race_group_agreement_manual2 = merged_data.groupby('Race_manual_2').apply(
    lambda x: (x['Race_manual_2'] == x['Race_automatic']).mean() * 100)

print("Race Agreement by Race (Manual 1 vs Automatic):")
print(race_group_agreement_manual1)

print("Race Agreement by Race (Manual 2 vs Automatic):")
print(race_group_agreement_manual2)

Race Agreement by Race (Manual 1 vs Automatic):
Race_manual_1
indian              0.000000
latino hispanic     0.000000
middle eastern      0.000000
white              66.666667
dtype: float64
Race Agreement by Race (Manual 2 vs Automatic):
Race_manual_2
indian               0.0
latino hispanic     50.0
middle eastern       0.0
white              100.0
dtype: float64

# 4. Overall Metrics:
To compute the overall accuracy between manual annotations and automatic predictions:

In [26]:
# Overall accuracy for Gender and Race (Manual 1 vs Automatic)
overall_accuracy_manual1 = ((merged_data['Gender_manual_1'] == merged_data['Gender_automatic']) & 
                            (merged_data['Race_manual_1'] == merged_data['Race_automatic'])).mean() * 100

# Overall accuracy for Gender and Race (Manual 2 vs Automatic)
overall_accuracy_manual2 = ((merged_data['Gender_manual_2'] == merged_data['Gender_automatic']) & 
                            (merged_data['Race_manual_2'] == merged_data['Race_automatic'])).mean() * 100

print(f"Overall Accuracy (Manual 1 vs Automatic): {overall_accuracy_manual1}%")
print(f"Overall Accuracy (Manual 2 vs Automatic): {overall_accuracy_manual2}%")

Overall Accuracy (Manual 1 vs Automatic): 33.33333333333333%
Overall Accuracy (Manual 2 vs Automatic): 33.33333333333333%

#  5. Inter-Annotator Agreement (IAA):
**Inter-annotator agreement (IAA)** is a general term referring to how much multiple annotators agree on their annotations. It measures the consistency between human annotators. The **Cohen’s Kappa score** is one way to compute inter-annotator agreement, but other methods like **Fleiss' Kappa** or **Krippendorff’s alpha** are also used for multi-annotator setups.




## 5. Cohen's Kappa:


The **Kappa score (Cohen's Kappa)** is a statistical measure used to evaluate the level of agreement between two annotators or classifiers, taking into account the possibility of agreement occurring by chance. It’s often used to assess the reliability of categorical data annotations.

### Cohen's Kappa Formula:
$$
\kappa = \frac{P_o - P_e}{1 - P_e}
$$

- $P_o$: The observed agreement (the percentage of times the annotators agreed).
- $P_e$: The expected agreement by chance (the percentage of agreement you would expect by random chance).

### Cohen's Kappa Score Interpretation:
- **1.0**: Perfect agreement.
- **0.8 to 1.0**: Almost perfect agreement.
- **0.6 to 0.8**: Substantial agreement.
- **0.4 to 0.6**: Moderate agreement.
- **0.2 to 0.4**: Fair agreement.
- **0.0 to 0.2**: Slight agreement.
- **<0.0**: Less than chance agreement (negative kappa).

In [27]:
from sklearn.metrics import cohen_kappa_score

# Calculate Cohen's Kappa for Age Group between Manual 1 and Automatic
kappa_manual1_automatic = cohen_kappa_score(merged_data['Age_group_manual_1'], merged_data['Age_group_automatic'])

# Calculate Cohen's Kappa for Age Group between Manual 2 and Automatic
kappa_manual2_automatic = cohen_kappa_score(merged_data['Age_group_manual_2'], merged_data['Age_group_automatic'])

# Calculate Cohen's Kappa for Age Group between Manual 1 and Manual 2
kappa_manual1_manual2 = cohen_kappa_score(merged_data['Age_group_manual_1'], merged_data['Age_group_manual_2'])

# Display the results
print(f"Cohen's Kappa (Manual 1 vs Automatic): {kappa_manual1_automatic}")
print(f"Cohen's Kappa (Manual 2 vs Automatic): {kappa_manual2_automatic}")
print(f"Cohen's Kappa (Manual 1 vs Manual 2): {kappa_manual1_manual2}")

Cohen's Kappa (Manual 1 vs Automatic): 0.4
Cohen's Kappa (Manual 2 vs Automatic): 0.19999999999999996
Cohen's Kappa (Manual 1 vs Manual 2): 0.3793103448275863